on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 

      - name: 'login to dockerhub'
        run: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.TEKEN}} 

      - name: 'build dockerhub image'
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/myimage . 

      - name: 'pushing to dockerhub'
        run: docker push ${{secrets.DOCKER_USERNAME}}/myimage  


